In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3]) 

In [5]:
print (a)

[1 2 3]


In [7]:
a = np.array([[1,2],[3,4]])

In [9]:
print(a)

[[1 2]
 [3 4]]


In [10]:
import numpy as np
dt = np.dtype(np.int32)
print dt

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(dt)? (Temp/ipykernel_9128/911392988.py, line 3)

In [11]:
import numpy as np

In [12]:
dt = np.dtype(np.int32)

In [13]:
print(dt)

int32


In [14]:
import numpy as np

In [15]:
dt = np.dtype('i4')

In [16]:
print(dt)

int32


In [17]:
dt = np.dtype(">i4")

In [18]:
dt = np.dtype([('age',np.int8)])

In [20]:
print (dt)

[('age', 'i1')]


In [21]:
import numpy

In [22]:
firstArray = numpy.empty([4,2], dtype = numpy.uint16) 

In [23]:
print(firstArray)

[[59546 22029]
 [42369 33933]
 [10739  4528]
 [27818 17198]]


In [24]:
print("Printing numpy array Attributes")

Printing numpy array Attributes


In [25]:
print("1> Array Shape is: ", firstArray.shape)

1> Array Shape is:  (4, 2)


In [26]:
print("2>. Array dimensions are ", firstArray.ndim)

2>. Array dimensions are  2


In [27]:
print("3>. Length of each element of array in bytes is ", firstArray.itemsize)

3>. Length of each element of array in bytes is  2


In [28]:
import numpy

In [29]:
firstarray = numpy.empty([4,2], dtype = numpy.uint16)

In [30]:
print(firstarray)

[[14032 10389]
 [  665     0]
 [    0     0]
 [    0     0]]


In [31]:
print("printing numpy array attributes")

printing numpy array attributes


In [32]:
print("1> Array shape is",firstArray.shape)

1> Array shape is (4, 2)


In [33]:
print("2>Array dimension is",firstArray.itemsize)

2>Array dimension is 2


In [34]:
print("3> Length of each array in byte is:"firstArray.itemsize)

SyntaxError: invalid syntax (Temp/ipykernel_9128/3005385284.py, line 1)

In [35]:
import numpy 

In [36]:
print("Creating 5 * 2 array using numpy.arrange ")

Creating 5 * 2 array using numpy.arrange 


In [37]:
sampleArray = numpy.arange(100, 200, 10)

In [38]:
sampleArray = sampleArray.reshape(5,2)

In [39]:
print(sampleArray)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [40]:
sampleArray = numpy.array([[11,22,33],[44,55,66]],[77,88,99]])

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (Temp/ipykernel_9128/1466928427.py, line 1)

In [42]:
sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])

In [43]:
print("Printing Array")

Printing Array


In [44]:
print(sampleArray)

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]


In [45]:
print("\n Printing array of odd rows and even columns")


 Printing array of odd rows and even columns


In [46]:
newArray = sampleArray[::2, 1::2]

In [47]:
print(newArray)

[[ 6 12]
 [30 36]
 [54 60]]


In [48]:
import numpy

In [49]:
arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])

In [50]:
arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])

In [51]:
resultarray = arrayone + arraytwo

NameError: name 'arrayone' is not defined

In [52]:
resultArray  = arrayOne + arrayTwo

In [53]:
print("addition of two arrays is \n")

addition of two arrays is 



In [54]:
print("resultArray")

resultArray


In [56]:
for num in numpy.nditer(resultArray, op_flags = ['readwrite']):
    num[...] = num*num
print("\nResult array after calculating the square root of all elements\n")
print(resultArray)


Result array after calculating the square root of all elements

[[ 400 1521 1089]
 [ 625  625  784]]


In [57]:
import numpy 

In [58]:
print("Creating 8X3 array using numpy.arange")

Creating 8X3 array using numpy.arange


In [59]:
sampleArray = numpy.arange(10, 34, 1)

In [60]:
sampleArray = sampleArray.reshape(8,3)

In [61]:
print (sampleArray)

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]


In [62]:
print("\nDividing 8X3 array into 4 sub array\n")


Dividing 8X3 array into 4 sub array



In [63]:
subArrays = numpy.split(sampleArray, 4) 

In [64]:
subArrays

[array([[10, 11, 12],
        [13, 14, 15]]),
 array([[16, 17, 18],
        [19, 20, 21]]),
 array([[22, 23, 24],
        [25, 26, 27]]),
 array([[28, 29, 30],
        [31, 32, 33]])]

In [65]:
import numpy

In [68]:
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 

In [69]:
print(sampleArray)

[[34 43 73]
 [82 22 12]
 [53 94 66]]


In [71]:
print("Sorting Original array by secoond row")

Sorting Original array by secoond row


In [72]:
sortArrayByColumn = sampleArray[sampleArray[:,1].argsort()]

In [73]:
print(sortArrayByColumn)

[[82 22 12]
 [34 43 73]
 [53 94 66]]


In [74]:
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

In [75]:
import numpy

In [76]:
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

In [77]:
print(sampleArray)

[[34 43 73]
 [82 22 12]
 [53 94 66]]


In [78]:
minOfAxisOne = numpy.amin(sampleArray, 1) 

In [79]:
print("Printing amin Of Axis 1")

Printing amin Of Axis 1


In [80]:
print("Printing amin Of Axis 1")

Printing amin Of Axis 1


In [81]:
print(minOfAxisOne)

[34 12 53]


In [82]:
maxOfAxisOne = numpy.amax(sampleArray, 0) 

In [83]:
print("Printing amax Of Axis 0")

Printing amax Of Axis 0


In [84]:
print(maxOfAxisOne)

[82 94 73]


In [85]:
print("Delete the second column from a given array and insert the new column in this place")

Delete the second column from a given array and insert the new column in this place


In [86]:
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

In [87]:
print(sampleArray)

[[34 43 73]
 [82 22 12]
 [53 94 66]]


In [88]:
newColumn = numpy.array([[10,10,10]])

In [89]:
print("Array after deleting column 2 on axis 1")

Array after deleting column 2 on axis 1


In [90]:
sampleArray = numpy.delete(sampleArray , 1, axis = 1) 

In [91]:
print (sampleArray)

[[34 73]
 [82 12]
 [53 66]]


In [92]:
arr = numpy.array([[10,10,10]])

In [93]:
print("Array after inserting column 2 on axis 1")

Array after inserting column 2 on axis 1


In [94]:
sampleArray = numpy.insert(sampleArray , 1, arr, axis = 1) 

In [95]:
print(sampleArray)

[[34 10 73]
 [82 10 12]
 [53 10 66]]


In [96]:
import pandas as pd 

In [98]:
file= pd.read_csv("C:/Users/Arunima/Downloads/Automobile_data.csv")

In [99]:
print("file")

file


In [100]:
file

index      company   body-style  wheel-base  length engine-type  \
0       0  alfa-romero  convertible        88.6   168.8        dohc   
1       1  alfa-romero  convertible        88.6   168.8        dohc   
2       2  alfa-romero    hatchback        94.5   171.2        ohcv   
3       3         audi        sedan        99.8   176.6         ohc   
4       4         audi        sedan        99.4   176.6         ohc   
..    ...          ...          ...         ...     ...         ...   
56     81   volkswagen        sedan        97.3   171.7         ohc   
57     82   volkswagen        sedan        97.3   171.7         ohc   
58     86   volkswagen        sedan        97.3   171.7         ohc   
59     87        volvo        sedan       104.3   188.8         ohc   
60     88        volvo        wagon       104.3   188.8         ohc   

   num-of-cylinders  horsepower  average-mileage    price  
0              four         111               21  13495.0  
1              four         111               21  16500.0  
2               six         154               19  16500.0  
3              four         102               24  13950.0  
4              five         115               18  17450.0  
..              ...         ...              ...      ...  
56             four          85               27   7975.0  
57             four          52               37   7995.0  
58             four         100               26   9995.0  
59             four         114               23  12940.0  
60             four         114               23  13415.0  

[61 rows x 10 columns]

In [102]:
file.head(5)

index      company   body-style  wheel-base  length engine-type  \
0      0  alfa-romero  convertible        88.6   168.8        dohc   
1      1  alfa-romero  convertible        88.6   168.8        dohc   
2      2  alfa-romero    hatchback        94.5   171.2        ohcv   
3      3         audi        sedan        99.8   176.6         ohc   
4      4         audi        sedan        99.4   176.6         ohc   

  num-of-cylinders  horsepower  average-mileage    price  
0             four         111               21  13495.0  
1             four         111               21  16500.0  
2              six         154               19  16500.0  
3             four         102               24  13950.0  
4             five         115               18  17450.0

In [103]:
file.tail(5)

index     company body-style  wheel-base  length engine-type  \
56     81  volkswagen      sedan        97.3   171.7         ohc   
57     82  volkswagen      sedan        97.3   171.7         ohc   
58     86  volkswagen      sedan        97.3   171.7         ohc   
59     87       volvo      sedan       104.3   188.8         ohc   
60     88       volvo      wagon       104.3   188.8         ohc   

   num-of-cylinders  horsepower  average-mileage    price  
56             four          85               27   7975.0  
57             four          52               37   7995.0  
58             four         100               26   9995.0  
59             four         114               23  12940.0  
60             four         114               23  13415.0

In [104]:
import pandas as pd

In [111]:
df = pd.read_csv("C:/Users/Arunima/Downloads/Sample4.csv",na_values="NAN")

In [112]:
print(df)

     Game Number   "Game Length"
0              1              30
1              2              29
2              3              31
3              4              16
4              5              24
..           ...             ...
995          996              24
996          997              21
997          998              47
998          999              30
999         1000              12

[1000 rows x 2 columns]


In [110]:
import pandas as pd

In [118]:
df = pd.read_csv("C:/Users/Arunima/Downloads/Sample4.csv",usecols =["Game Number"])

In [115]:
df

Game Number
0              1
1              2
2              3
3              4
4              5
..           ...
995          996
996          997
997          998
998          999
999         1000

[1000 rows x 1 columns]

In [119]:
import pandas as pd

In [120]:
df = pd.read_csv("C:/Users/Arunima/Downloads/Automobile_data.csv") 

In [121]:
print(df.to_string())

    index        company   body-style  wheel-base  length engine-type num-of-cylinders  horsepower  average-mileage    price
0       0    alfa-romero  convertible        88.6   168.8        dohc             four         111               21  13495.0
1       1    alfa-romero  convertible        88.6   168.8        dohc             four         111               21  16500.0
2       2    alfa-romero    hatchback        94.5   171.2        ohcv              six         154               19  16500.0
3       3           audi        sedan        99.8   176.6         ohc             four         102               24  13950.0
4       4           audi        sedan        99.4   176.6         ohc             five         115               18  17450.0
5       5           audi        sedan        99.8   177.3         ohc             five         110               19  15250.0
6       6           audi        wagon       105.8   192.7         ohc             five         110               19  18920.0


In [132]:
df = pd.read_csv("C:/Users/Arunima/Downloads/Automobile_data.csv")

In [135]:
df['wheel-base'].value_counts()

94.5     9
95.7     6
97.3     4
93.7     4
101.2    3
110.0    3
93.1     3
96.5     3
88.6     2
113.0    2
89.5     2
96.3     2
104.3    2
103.5    2
99.8     2
94.3     1
88.4     1
95.3     1
104.9    1
120.9    1
112.0    1
100.4    1
105.8    1
98.4     1
99.4     1
104.5    1
102.0    1
Name: wheel-base, dtype: int64

In [136]:
import pandas as pd

In [137]:
results = pd.read_csv("C:/Users/Arunima/Downloads/Automobile_data.csv")

In [138]:
print("Number Results",len(results))

Number Results 61


In [147]:
rowcount  = 0
#iterating through the whole file
for row in open("C:/Users/Arunima/Downloads/Automobile_data.csv"):
  rowcount+= 1
 #printing the result
print("Number of lines present:-", rowcount)

Number of lines present:- 62


In [148]:
import pandas as pd 

In [149]:
df = pd.read_csv("C:/Users/Arunima/Downloads/Automobile_data.csv")

In [150]:
car_Manufacturers = df.groupby('company')

In [151]:
priceDf = car_Manufacturers['company','price'].max()

C:\Users\Arunima\AppData\Local\Temp/ipykernel_9128/696153469.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  priceDf = car_Manufacturers['company','price'].max()


In [152]:
priceDf

company    price
company                              
alfa-romero      alfa-romero  16500.0
audi                    audi  18920.0
bmw                      bmw  41315.0
chevrolet          chevrolet   6575.0
dodge                  dodge   6377.0
honda                  honda  12945.0
isuzu                  isuzu   6785.0
jaguar                jaguar  36000.0
mazda                  mazda  18344.0
mercedes-benz  mercedes-benz  45400.0
mitsubishi        mitsubishi   8189.0
nissan                nissan  13499.0
porsche              porsche  37028.0
toyota                toyota  15750.0
volkswagen        volkswagen   9995.0
volvo                  volvo  13415.0

In [154]:
df = pd.read_csv("C:/Users/Arunima/Downloads/Automobile_data.csv")

In [155]:
car_Manufacturers = df.groupby('company')

In [156]:
mileageDf = car_Manufacturers['company','average-mileage'].mean()

C:\Users\Arunima\AppData\Local\Temp/ipykernel_9128/2566049016.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  mileageDf = car_Manufacturers['company','average-mileage'].mean()


In [158]:
mileageDf

average-mileage
company                       
alfa-romero          20.333333
audi                 20.000000
bmw                  19.000000
chevrolet            41.000000
dodge                31.000000
honda                26.333333
isuzu                33.333333
jaguar               14.333333
mazda                28.000000
mercedes-benz        18.000000
mitsubishi           29.500000
nissan               31.400000
porsche              17.000000
toyota               28.714286
volkswagen           31.750000
volvo                23.000000

In [159]:
GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]}
japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}

In [160]:
GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]}

In [161]:
carsDf1 = pd.DataFrame.from_dict(GermanCars)

In [162]:
carsDf1

Company   Price
0      Ford   23845
1  Mercedes  171995
2       BMV  135925
3      Audi   71400

In [163]:
japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}

In [164]:
carsDf2 = pd.DataFrame.from_dict(japaneseCars)

In [165]:
carsDf = pd.concat([carsDf1, carsDf2], keys=["Germany", "Japan"])

In [166]:
carsDf

Company   Price
Germany 0         Ford   23845
        1     Mercedes  171995
        2          BMV  135925
        3         Audi   71400
Japan   0       Toyota   29995
        1        Honda   23600
        2       Nissan   61500
        3  Mitsubishi    58900

In [168]:
car_Horsepower = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'horsepower': [141, 80, 182 , 160]}

In [169]:
carsHorsepowerDf = pd.DataFrame.from_dict(car_Horsepower)

NameError: name 'carPriceDf' is not defined

In [177]:
import pandas as pd

In [178]:
Car_Price = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'Price': [23845, 17995, 135925 , 71400]}

In [179]:
carPriceDf = pd.DataFrame.from_dict(Car_Price)

In [180]:
carPriceDf

Company   Price
0  Toyota   23845
1   Honda   17995
2     BMV  135925
3    Audi   71400

In [181]:
car_Horsepower = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'horsepower': [141, 80, 182 , 160]}

In [182]:
carsHorsepowerDf = pd.DataFrame.from_dict(car_Horsepower)

In [183]:
carsDf = pd.merge(carPriceDf, carsHorsepowerDf, on="Company")

In [184]:
carsDf

Company   Price  horsepower
0  Toyota   23845         141
1   Honda   17995          80
2     BMV  135925         182
3    Audi   71400         160

In [185]:
str1 = "James"

In [186]:
print("The name of the employee is",str1)

The name of the employee is James


In [187]:
res= str1[0]

In [189]:
print(res)

J


In [190]:
l = len(str1)

In [191]:
mi = int(l / 2)

In [192]:
res = res + str1[mi]

In [193]:
res = res + str1[l - 1]

In [194]:
print("New String:", res)

New String: Jms


In [202]:
def middle_char(txt):
  return txt[(len(txt)-1)//2:(len(txt)+2)//2]

txt = "JhonDipPeta"
print("Original string: ",txt)
print("Middle character(s) of the said string: ",middle_char(txt))


Original string:  JhonDipPeta
Middle character(s) of the said string:  i


In [207]:
def get_middle_three_chars(str1):
    print("Original String is", str1)

    # first get middle index number
    mi = int(len(str1) / 2)

    # use string slicing to get result characters
    res = str1[mi - 1:mi + 2]
    print("Middle three chars are:", res)

get_middle_three_chars("JhonDipPeta")
get_middle_three_chars("JaSonAy")

Original String is JhonDipPeta
Middle three chars are: Dip
Original String is JaSonAy
Middle three chars are: Son


In [209]:
def append_middle(s1, s2):
    print("Original Strings are", s1, s2)

    # middle index number of s1
    mi = int(len(s1) / 2)

    # get character from 0 to the middle index number from s1
    x = s1[:mi:]
    # concatenate s2 to it
    x = x + s2
    # append remaining character from s1
    x = x + s1[mi:]
    print("After appending new string in middle:", x)

append_middle("Ault", "Kelly")

Original Strings are Ault Kelly
After appending new string in middle: AuKellylt


In [210]:
def mix_string(s1, s2):
    first_char = s1[0] + s2[0]
    middle_char = s1[int(len(s1) / 2):int(len(s1) / 2) + 1] + s2[int(len(s2) / 2):int(len(s2) / 2) + 1]
    last_char = s1[len(s1) - 1] + s2[len(s2) - 1]
    middle_char = s1[int(len(s1) / 2):int(len(s1) / 2) + 1] + s2[int(len(s2) / 2):int(len(s2) / 2) + 1]

    # get last character from both string
    last_char = s1[len(s1) - 1] + s2[len(s2) - 1]

    # add all
    res = first_char + middle_char + last_char
    print("Mix String is ", res)

s1 = "America"
s2 = "Japan"
mix_string(s1, s2)

Mix String is  AJrpan


In [211]:
str1 = "PYnAtivE"

In [212]:
print('Original String:', str1)

Original String: PYnAtivE


In [215]:
str1 = "PYnAtivE"
print('Original String:', str1)
lower = []
upper = []
for char in str1:
    if char.islower():
        # add lowercase characters to lower list
        lower.append(char)
    else:
        # add uppercase characters to lower list
        upper.append(char)

# Join both list
sorted_str = ''.join(lower + upper)
print('Result:', sorted_str)


Original String: PYnAtivE
Result: ntivPYAE


In [312]:
from collections import Counter
  
# initializing string 
test_str = "GeeksforGeeks"
  
# using collections.Counter() to get count 
# counting e 
count = Counter(test_str)
  
# printing result 
print ("Count of e in GeeksforGeeks is : "
                       +  str(count['e']))

TypeError: 'str' object is not callable

In [221]:
str1 = "Welcome to USA. usa awesome, isn't it?"

In [222]:
count = Counter(str1)

TypeError: 'builtin_function_or_method' object is not iterable

In [223]:
print ("Count of USA in this list: "
                      + str1(count['USA']))

NameError: name 'count' is not defined

In [309]:
from collections import Counter
  
# initializing string 
test_str = "GeeksforGeeks"
  
# using collections.Counter() to get count 
# counting e 
count = Counter(test_str)
  
# printing result 
print ("Count of e in GeeksforGeeks is : "
                       +  str(count['e']))

TypeError: 'str' object is not callable

In [301]:
str1 = "Welcome to usa. usa awesome, isn't it?"
sub_string ="usa"
count = str1.count(sub_string.lower())
print("The occurance of USA is",count)

The occurance of USA is 2


In [228]:
str1 = "PYnative"
print("Original String is:", str1)
str2 = reversed(str1)

Original String is: PYnative


In [242]:
str1 = "PYnative"
print("Original String is:", str1)
str2 = str1[::-1]
print("Reversed String is:", str2)

Original String is: PYnative
Reversed String is: evitanYP


In [230]:
from collections to import Counter

SyntaxError: invalid syntax (Temp/ipykernel_9128/2435116448.py, line 1)

In [231]:
from collections import Counter

In [294]:
str = "Apple"

In [233]:
res = Counter("Apple")

In [234]:
print(res)

Counter({'p': 2, 'A': 1, 'l': 1, 'e': 1})


Counter({'s': 1, 't': 1, 'r': 1, '1': 1})


IndentationError: unexpected indent (Temp/ipykernel_9128/1965823490.py, line 4)

In [241]:
input_str = "PYnative29@#8496"
total = 0
cnt = 0
for char in input_str:
    if char.isdigit():
        total += int(char)
        cnt += 1

# average = sum / count of digits
avg = total / cnt
print("Sum is:", total, "Average is ", avg)

Sum is: 38 Average is  6.333333333333333


In [244]:
str = "Emma is a data scientist who knows Python. Emma works at google."
print("Original String is:", str1)
index = str.rfind("Emma")
print("Last occurrence of Emma starts at index:", index)


Original String is: PYnative
Last occurrence of Emma starts at index: 43


In [245]:
string = "Emma is a data scientist"
print("The orginal strng is",string)

The orginal strng is Emma is a data scientist


In [247]:
sub_string = string.split(" -")
print("Display any substring")
for sub in substring :
    print(sub)

NameError: name 'string' is not defined

In [248]:
str1 = "Emma-is-a-data-scientist"
print("Original String is:", str1)

# split string
sub_strings = str1.split("-")

print("Displaying each substring")
for sub in sub_strings:
    print(sub)

Original String is: Emma-is-a-data-scientist
Displaying each substring
Emma
is
a
data
scientist


In [249]:
str_list = ["Emma", "Jon", "", "Kelly", None, "Eric", ""]

In [251]:
new_str_list = list(filter(None,str_list))

In [252]:
print("After removing empty string")

After removing empty string


In [253]:
print(new_str_list)

['Emma', 'Jon', 'Kelly', 'Eric']


In [254]:
sampletuple= tuple(('Gessa',20,78,54))

In [255]:
print(sampletuple)

('Gessa', 20, 78, 54)


In [258]:
single_tuple_datatype = ("Hello",)

In [260]:
print(type(single_tuple_datatype))

<class 'tuple'>


In [263]:
tuple = ('p','y','t','h','o','n')

In [264]:
print(len(tuple))

6


TypeError: 'tuple' object is not callable

In [267]:
sample_tuple = tuple((1, 2, 3, "Hello", [4, 8, 16]))

TypeError: 'tuple' object is not callable

In [271]:
tuple1 = ('P', 'Y', 'T', 'H', 'O', 'N')
for i in range(4):
    print(tuple1[i])

P
Y
T
H


In [275]:
tuple1 = ('P', 'Y', 'T', 'H', 'O', 'N')
for i in range(4):
    print(tuple1[i])

P
Y
T
H


In [276]:
tuple1 = ('P', 'Y', 'T', 'H', 'O', 'N')

In [278]:
print(tuple1[2])

T


In [281]:
str1 = "Emma is a data scientist"
print ("String is",str1)

String is Emma is a data scientist


Emma is a data scientist


In [284]:
str1 = "Emma-is-a-data-scientist"
print("Original String is:", str1)

# split string
sub_strings = str1.split("-")

print("Displaying each substring")
for sub in sub_strings:
    print(sub)

Original String is: Emma-is-a-data-scientist
Displaying each substring
Emma
is
a
data
scientist


In [287]:
str1 = "Emma-is-a-data-scientist"
print("Original String is:",str1)

sub_strings = str1.split("-")
for sub in sub_strings:
    print(sub)

Original String is: Emma-is-a-data-scientist
Emma
is
a
data
scientist


In [288]:
str_list = ["Emma", "Jon", "", "Kelly", None, "Eric", ""]

In [289]:
new_str_list = list(filter(None, str_list))

In [290]:
print("After removing empty string")

After removing empty string


In [291]:
print(new_str_list)

['Emma', 'Jon', 'Kelly', 'Eric']


In [292]:
str = "Emma is a data scientist who knows Python. Emma works at google."
print("Original String is:", str1)
index = str.rfind("Emma")
print("Last occurrence of Emma starts at index:", index)

Original String is: Emma-is-a-data-scientist
Last occurrence of Emma starts at index: 43


In [293]:
str = "Emma is a data scientist who knows python. Emma works at google."
print("Original String is",str1)
index = str.rfind("Emma")
print("Last occurance of Emma starts at index",index)

Original String is Emma-is-a-data-scientist
Last occurance of Emma starts at index 43


In [295]:
from collections import Counter

In [296]:
str = "Apple"

In [297]:
res = Counter(str)

In [298]:
print(res)

Counter({'p': 2, 'A': 1, 'l': 1, 'e': 1})


In [299]:
str1 = "Arunima"
print ("The original string is", str1)
new_str = str1[::-1]
print("The new string is",new_str)

The original string is Arunima
The new string is aminurA


In [302]:
str1 = "Welcome to usa. usa awesome, isn't it?"
sub_string ="usa"
count = str1.count(sub_string.lower())
print("The occurance of USA is",count)

The occurance of USA is 2


In [306]:
str1 = "Welcome to asia, asia is hot, interms of asia, is not it?"
sub_string = "asia"
tmp_str1 = str1.lower()
count = tmp_str1.count(sub_string.lower())
print("The occurance of asia is", count)

The occurance of asia is 3


TypeError: 'str' object is not callable

TypeError: 'str' object is not callable

In [314]:
str1 = "PYnAtivE"
print('Original String:', str1)
lower = []
upper = []
for char in str1:
    if char.islower():
        # add lowercase characters to lower list
        lower.append(char)
    else:
        # add uppercase characters to lower list
        upper.append(char)

# Join both list
sorted_str = ''.join(lower + upper)
print('Result:', sorted_str)


Original String: PYnAtivE
Result: ntivPYAE


In [317]:
str1 = "PYnAtive"
print('Oringinal String',str1)
lower = []
upper = []
for char in str1:
    if char.islower():
        lower.append(char)
    else:
        upper.append(char)
sorted_str = ''.join(lower + upper)
print('Result:',sorted_str)

Oringinal String PYnAtive
Result: ntivePYA


In [320]:
 str1 = "PYnAtive"
print('Oringinal String',str1)
lower = []
upper = []
for char in str1:
    if char.islower():
        lower.append(char)
    else:
        upper.append(char)
sorted_str = ''.join(lower + upper)
print('Result:',sorted_str)

Oringinal String PYnAtive
Result: ntivePYA
